### ISSUE TITLE
Using KDBC SQLite & Modelling issue

### ISSUE THREAD

**Issue by Yadarma** [edvin/kdbc#13]
Dear Edvin, if you could provide an example starting sqlite connection to an already existed/created db in the base directory, it'll be very helpful. Thank you!

Should I use 2 models. One for JavaFX properties and the other for Database POJOS like that? What is the best approach?
model1 (JavaFX properties)

```
class UserFX {
    var username by property<String>()
    fun usernameProperty() = getProperty(UserFX::username)

    var password by property<String>()
    fun passwordProperty() = getProperty(UserFX::password)

}
class UserModel : ItemViewModel<UserFX>(UserFX()) {
    val username: StringProperty = bind { item?.usernameProperty() }
    val password: StringProperty = bind { item?.passwordProperty() }
}
```
model2(Database POJOs)
```
data class User(var id: Int, var username: String, var password: String, var firstName: String, var lastName: String)

class UserTable : Table("User") {
    val username = column<String>("username")
    val password = column<String>("password")
}

class SelectUser : Query<User>() {
    val u = UserTable()
    init {
        select(u.username, u.password)
        from(u)
    }
    override fun get() = User(u.username().toString(), u.password().toString())
}
```
If no, how do I combine the two models into one ?

**Comment by edvin** [comment]
You don't nede the `data class User`, just create instances of `UserFX` inside `get` in the query.

SQLite connection would be done in exactly the same way as for any other database framework, there is nothing KDBC specific about the database connection at all. Did you run into trouble when setting it up? If so, I think it's better to look at your specific use case.

**Comment by Yadarma** [comment]
` override fun get() = UserFX()` gave me java.lang.NullPointerException??? sorry but could you illustrate with code, please???

As for starting connection:
```
    init {
        val ds = SQLiteDataSource()
        ds.url = "jdbc:sqlite:PATH_TO_DB"
        KDBC.setDataSource(ds)
        dbUsers = SelectUser().list()
    }
```
worked successfully for me.

**Comment by edvin** [comment]
UserFX like you posted it above will not throw an NPE when instantiated. Post your complete code and the complete stack trace :)

**Comment by Yadarma** [comment]
```
java.lang.NullPointerException
	at org.examples.view.LoginView$root$1$2$2$1$1$1.invoke(LoginView.kt:51)
	at org.examples.view.LoginView$root$1$2$2$1$1$1.invoke(LoginView.kt:17)
	at tornadofx.ViewModel.commit(ViewModel.kt:240)
	at tornadofx.ViewModel.commit(ViewModel.kt:207)
	at org.examples.view.LoginView$root$1$2$2$1$1.invoke(LoginView.kt:47)
	at org.examples.view.LoginView$root$1$2$2$1$1.invoke(LoginView.kt:17)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt:521)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8413)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
```

UserFX.kt
```
class UserFX {
    
    var id by property<Int>()
    fun idProperty() = getProperty(UserFX::id)

    var username by property<String>()
    fun usernameProperty() = getProperty(UserFX::username)

    var password by property<String>()
    fun passwordProperty() = getProperty(UserFX::password)

    var firstName by property<String>()
    fun firstNameProperty() = getProperty(UserFX::firstName)

    var lastName by property<String>()
    fun lastNameProperty() = getProperty(UserFX::lastName)

}


class UserModel : ItemViewModel<UserFX>(UserFX()) {
    val id: Property<Int> = bind { item?.idProperty() }
    val username: StringProperty = bind { item?.usernameProperty() }
    val password: StringProperty = bind { item?.passwordProperty() }
    val firstName: StringProperty = bind { item?.firstNameProperty() }
    val lastName: StringProperty = bind { item?.lastNameProperty() }
}


class UserTable : Table("User") {
    val id = column<Int>("id")
    val username = column<String>("username")
    val password = column<String>("password")
    val firstName = column<String>("firstName")
    val lastName = column<String>("lastName")
}

class SelectUser : Query<UserFX>() {
    val u = UserTable()

    init {
        select(u.id, u.username, u.password, u.firstName, u.lastName)
        from(u)
    }
    
    override fun get() = UserFX()

    fun byId(id: Int) = first {
        where {
            u.id `=` id
        }
    }
}
```

LoginView.kt
```
button("Login") {
                    action {
                        model.commit {
                            var message = "Login failed. Try again!"
                            val userFX = model.item
                            for (u in dbUsers) {
               ***            if (u.username.equals(userFX.username) && u.password.equals(userFX.password)) {
                                    message = "Login success. Welcome ${u.firstName} ${u.lastName}"
                                }
                            }
                            Notifications.create()
                                    .title("Login Status!")
                                    .text(message)
                                    .owner(this)
                                    .showInformation()
                        }
                    }
                    enableWhen(model.valid)
                }
```

**Comment by Yadarma** [comment]
However, if I used UserModel NOT UserFX in the Query like
```
class SelectUser : Query<UserModel>() {
    val u = UserTable() 
    init {
        select(u.id, u.username, u.password, u.firstName, u.lastName)
        from(u)
    }
    override fun get() = UserModel()
}
```
I don't get NPE but the values are not populated into the fields
`StringProperty [bean: org.examples.model.UserModel@739b9e85, value: null]`

**Comment by edvin** [comment]
I think you've missed the point of the `get` function in your query. In `get`, you're supposed to populate the object you return with the values from the query, available in the table object (`u`). Look at the examples. Furthermore, you want to populate UserFX, not your model.

**Comment by Yadarma** [comment]
I have done what you just said in the comment before the last one of mine using `override fun get() = UserFX()` but I got NPE anyway.

**Comment by edvin** [comment]
Your NPE is coming from LoginView.kt:51, not from `get` being called.

**Comment by edvin** [comment]
Try skipping the UI until you can get it to work, I don't think the NPE has anything to do with `get`, but rather your UI.

**Comment by Yadarma** [comment]
I will be OK with my workaround. I don't know if you could make us an example in the book/wiki for that case when you are free. Thanks anyway for support!

**Comment by edvin** [comment]
OK, I'll start working on KDBC again in a little while and be sure to make lots of examples :)

**Comment by Yadarma** [comment]
That'll be great. Waiting for them 👍
